//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Paisa_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisenoTroquel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DisenoTroquel()
        {
            this.ProtocoloDetalleMaterial = new HashSet<ProtocoloDetalleMaterial>();
        }
    
        public int idDisenoTroquel { get; set; }
        public string server { get; set; }
        public string ruta { get; set; }
        public string nombreArchivo { get; set; }
        public string extension { get; set; }
        public Nullable<int> ultimoUsr { get; set; }
        public Nullable<System.DateTime> ultimaFec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProtocoloDetalleMaterial> ProtocoloDetalleMaterial { get; set; }
    }
}
