//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Paisa_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenDetalleImpresion
    {
        public int idImagenDetImpresion { get; set; }
        public int idProtocoloDetImpresion { get; set; }
        public string server { get; set; }
        public string descripcionImg { get; set; }
        public string ruta { get; set; }
        public string nombreArchivo { get; set; }
        public string extension { get; set; }
        public Nullable<int> ultimoUsr { get; set; }
        public Nullable<System.DateTime> ultimaFec { get; set; }
    }
}
