//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Paisa_v1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class paisaEntities : DbContext
    {
        public paisaEntities()
            : base("name=paisaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SEC_PermisoConTipoUsuario> SEC_PermisoConTipoUsuario { get; set; }
        public virtual DbSet<SEC_Permisos> SEC_Permisos { get; set; }
        public virtual DbSet<SEC_TipoUsuario> SEC_TipoUsuario { get; set; }
        public virtual DbSet<SEC_Usuario> SEC_Usuario { get; set; }
        public virtual DbSet<EspecificacionImpresion> EspecificacionImpresion { get; set; }
        public virtual DbSet<RodilloImpresion> RodilloImpresion { get; set; }
        public virtual DbSet<TipoImpresion> TipoImpresion { get; set; }
    
        public virtual ObjectResult<sp_V_SEC_Usuario_Result> sp_V_SEC_Usuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_V_SEC_Usuario_Result>("sp_V_SEC_Usuario");
        }
    
        public virtual ObjectResult<sp_P_SEC_Usuario_Result> sp_P_SEC_Usuario(string codUsuario, string password)
        {
            var codUsuarioParameter = codUsuario != null ?
                new ObjectParameter("codUsuario", codUsuario) :
                new ObjectParameter("codUsuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_P_SEC_Usuario_Result>("sp_P_SEC_Usuario", codUsuarioParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_P_SEC_Usuario1_Result> sp_P_SEC_Usuario1(string codUsuario, string password)
        {
            var codUsuarioParameter = codUsuario != null ?
                new ObjectParameter("codUsuario", codUsuario) :
                new ObjectParameter("codUsuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_P_SEC_Usuario1_Result>("sp_P_SEC_Usuario1", codUsuarioParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_V_SEC_Usuario1_Result> sp_V_SEC_Usuario1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_V_SEC_Usuario1_Result>("sp_V_SEC_Usuario1");
        }
    
        public virtual ObjectResult<sp_P_SEC_Usuario2_Result> sp_P_SEC_Usuario2(string codUsuario, string password)
        {
            var codUsuarioParameter = codUsuario != null ?
                new ObjectParameter("codUsuario", codUsuario) :
                new ObjectParameter("codUsuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_P_SEC_Usuario2_Result>("sp_P_SEC_Usuario2", codUsuarioParameter, passwordParameter);
        }
    }
}
