//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Paisa_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocoloDetalleMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProtocoloDetalleMaterial()
        {
            this.AnchoSinFuelles = new HashSet<AnchoSinFuelles>();
            this.Calibre2Caras = new HashSet<Calibre2Caras>();
            this.Fuelle = new HashSet<Fuelle>();
            this.LargoSinFuelles = new HashSet<LargoSinFuelles>();
        }
    
        public int IdProtocoloDetMat { get; set; }
        public int IdEncabezado { get; set; }
        public string idMaterial { get; set; }
        public string ColorPelicula { get; set; }
        public string idPresentacion { get; set; }
        public string OtroPresentacion { get; set; }
        public string idTipoSello { get; set; }
        public Nullable<decimal> MedidaPulgada { get; set; }
        public Nullable<bool> EsMuestra { get; set; }
        public Nullable<bool> EsFibrilado { get; set; }
        public Nullable<decimal> Rendimiento { get; set; }
        public Nullable<decimal> PesoBobina { get; set; }
        public Nullable<decimal> PesoBobinaTolerancia { get; set; }
        public Nullable<bool> EsTratadoCorona { get; set; }
        public string idTratadoCorona { get; set; }
        public string RendPorBobinaUniMed { get; set; }
        public Nullable<decimal> RendPorBobinaValor { get; set; }
        public Nullable<bool> Embosado { get; set; }
        public Nullable<decimal> MedidaTraslape { get; set; }
        public Nullable<bool> Ubicacion { get; set; }
        public Nullable<decimal> MediaPestana { get; set; }
        public Nullable<bool> EsAdhesivoCierre { get; set; }
        public Nullable<int> idDisenoTroquel { get; set; }
        public Nullable<bool> Perforacion { get; set; }
        public Nullable<int> idTipoEmbobinado { get; set; }
        public string AplicacionProdUso { get; set; }
        public Nullable<bool> EsPeso { get; set; }
        public string PresoPromUniMed { get; set; }
        public Nullable<decimal> PesoProm { get; set; }
        public Nullable<int> ultimoUsr { get; set; }
        public Nullable<System.DateTime> ultimaFec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnchoSinFuelles> AnchoSinFuelles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calibre2Caras> Calibre2Caras { get; set; }
        public virtual DisenoTroquel DisenoTroquel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fuelle> Fuelle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LargoSinFuelles> LargoSinFuelles { get; set; }
        public virtual Material Material { get; set; }
        public virtual Presentacion Presentacion { get; set; }
        public virtual ProtocoloEncabezado ProtocoloEncabezado { get; set; }
        public virtual TipoEmbobinado TipoEmbobinado { get; set; }
        public virtual TipoSello TipoSello { get; set; }
        public virtual TratadoCorona TratadoCorona { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual UnidadMedida UnidadMedida1 { get; set; }
    }
}
