//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Paisa_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocoloDetalleExigenciasCliente
    {
        public int idProtocoloDetExiCliente { get; set; }
        public int IdEncabezado { get; set; }
        public Nullable<int> idTipoExigencia { get; set; }
        public string Otros { get; set; }
        public Nullable<int> ultimoUsr { get; set; }
        public Nullable<System.DateTime> ultimaFec { get; set; }
    
        public virtual ProtocoloEncabezado ProtocoloEncabezado { get; set; }
        public virtual TipoExigencia TipoExigencia { get; set; }
    }
}
