//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Paisa_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocoloEncabezado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProtocoloEncabezado()
        {
            this.ProtocoloDetalleEmpaque = new HashSet<ProtocoloDetalleEmpaque>();
            this.ProtocoloDetalleExigenciasCliente = new HashSet<ProtocoloDetalleExigenciasCliente>();
            this.ProtocoloDetalleFardo = new HashSet<ProtocoloDetalleFardo>();
            this.ProtocoloDetalleImpresion = new HashSet<ProtocoloDetalleImpresion>();
            this.ProtocoloDetalleMaterial = new HashSet<ProtocoloDetalleMaterial>();
        }
    
        public int IdEncabezado { get; set; }
        public string codigoVendedor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NombreProducto { get; set; }
        public string CodigoCliente { get; set; }
        public string CVE_ART { get; set; }
        public Nullable<int> Version { get; set; }
        public string ObservacionesGenerales { get; set; }
        public Nullable<bool> EsAutorizado { get; set; }
        public string usuarioAutoriza { get; set; }
        public Nullable<System.DateTime> fechaAutoriza { get; set; }
        public Nullable<bool> EstaProduccion { get; set; }
        public string usuarioProduccion { get; set; }
        public Nullable<System.DateTime> fechaProduccion { get; set; }
        public Nullable<int> ultimoUsr { get; set; }
        public Nullable<System.DateTime> ultimaFec { get; set; }
        public string Empresa { get; set; }
        public string Versiona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProtocoloDetalleEmpaque> ProtocoloDetalleEmpaque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProtocoloDetalleExigenciasCliente> ProtocoloDetalleExigenciasCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProtocoloDetalleFardo> ProtocoloDetalleFardo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProtocoloDetalleImpresion> ProtocoloDetalleImpresion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProtocoloDetalleMaterial> ProtocoloDetalleMaterial { get; set; }
    }
}
