//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Paisa_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocoloDetalleEmpaque
    {
        public int idProtocoloDetEmpaque { get; set; }
        public int IdEncabezado { get; set; }
        public Nullable<decimal> CantEmpaquePrim { get; set; }
        public Nullable<decimal> CantPaqueteEmpaqueSec { get; set; }
        public Nullable<decimal> MillaresPorFardo { get; set; }
        public Nullable<int> idTipoTermoE { get; set; }
        public Nullable<int> idTipoCaja { get; set; }
        public Nullable<int> idTipoTape { get; set; }
        public string Otros { get; set; }
        public Nullable<int> ultimoUsr { get; set; }
        public Nullable<System.DateTime> ultimaFec { get; set; }
    
        public virtual TipoTermoencogible TipoTermoencogible { get; set; }
        public virtual ProtocoloEncabezado ProtocoloEncabezado { get; set; }
        public virtual TipoCaja TipoCaja { get; set; }
        public virtual TipoTape TipoTape { get; set; }
    }
}
