//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Paisa_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RodilloImpresion
    {
        public int idRodilloImpresion { get; set; }
        public Nullable<int> CantidadRodxMedida { get; set; }
        public string Engranaje { get; set; }
        public string Pulgadas { get; set; }
        public Nullable<int> CantColores { get; set; }
        public Nullable<int> ultimoUsr { get; set; }
        public Nullable<System.DateTime> ultimaFec { get; set; }
    }
}
