//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Paisa_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_Permisos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEC_Permisos()
        {
            this.SEC_PermisoConTipoUsuario = new HashSet<SEC_PermisoConTipoUsuario>();
        }
    
        public int idPermiso { get; set; }
        public string IdObjeto { get; set; }
        public string idPadre { get; set; }
        public string textoAMostrar { get; set; }
        public Nullable<System.DateTime> ultimaFecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_PermisoConTipoUsuario> SEC_PermisoConTipoUsuario { get; set; }
    }
}
